import Head from 'next/head';
import Link from 'next/link';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import Button from '@mui/material/Button';

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Blog Engine</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Typography variant='h3' gutterBottom>
        Welcome to the Blog Engine
      </Typography>
      <Grid container spacing={3}>
        <Grid item>
          <Button variant='contained' color='primary' href='/about'>
            About
          </Button>
        </Grid>
        <Grid item>
          <Button variant='contained' color='primary' href='/categories'>
            Categories
          </Button>
        </Grid>
        <Grid item>
          <Button variant='contained' color='primary' href='/posts'>
            Posts
          </Button>
        </Grid>
      </Grid>
    </Container>
  );
}
