version: "3.8"

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ../backend/BlogEngine.Api:/src
      - ~/.microsoft/usersecrets/:/root/.microsoft/usersecrets

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../frontend:/app
      - /app/node_modules
